# Generated by Django 4.1.1 on 2022-11-02 15:38

import chronos.watches.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watch',
            options={},
        ),
        migrations.RemoveField(
            model_name='watch',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='watch',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[chronos.watches.validators.file_size]),
        ),
    ]
