# Generated by Django 4.1.1 on 2022-11-02 15:40

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watches', '0002_alter_watch_options_remove_watch_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch',
            name='likes',
            field=models.ManyToManyField(related_name='watch_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
