# Generated by Django 4.1.1 on 2022-11-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0003_watch_created_at_watch_likes_watch_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watch',
            options={'verbose_name_plural': 'watches'},
        ),
    ]
